import 'package:flutter/material.dart';

/// Localization resources for the auth / sign-up / OTP / documents / verification
/// flows. Every user-visible string lives here (no copy inside widgets).
/// ARABIC IS DRAFT COPY and needs native / business review before launch.
class FlowStrings {
  final bool ar;
  const FlowStrings._(this.ar);
  @visibleForTesting
  const FlowStrings.forTest(this.ar);
  static FlowStrings of(BuildContext c) => FlowStrings._(Localizations.localeOf(c).languageCode == 'ar');

  String t(String key, [Map<String, String> args = const {}]) {
    final e = _s[key];
    assert(e != null, 'Missing string: $key');
    var out = e == null ? key : (ar ? e.$2 : e.$1);
    args.forEach((k, v) => out = out.replaceAll('{$k}', v));
    return out;
  }

  static Iterable<String> get keys => _s.keys;
}

const Map<String, (String, String)> _s = {
  // common
  'common.back': ('Back', 'رجوع'),
  'common.next': ('Next', 'التالي'),
  'common.continue': ('Continue', 'متابعة'),
  'common.cancel': ('Cancel', 'إلغاء'),
  'common.retry': ('Try again', 'إعادة المحاولة'),
  'common.demo': ('DEMO DATA', 'بيانات تجريبية'),
  'common.networkError': ('We could not reach AQARATI. Check your connection and try again.', 'تعذّر الوصول إلى عقاراتي. تحقق من اتصالك وحاول مرة أخرى.'),
  'common.genericError': ('Something went wrong. Please try again.', 'حدث خطأ ما. حاول مرة أخرى.'),
  'common.loading': ('Loading', 'جارٍ التحميل'),
  'common.required': ('This field is required.', 'هذا الحقل مطلوب.'),
  // fields
  'field.firstName': ('First name', 'الاسم الأول'),
  'field.lastName': ('Last name', 'اسم العائلة'),
  'field.phone': ('Mobile number', 'رقم الجوال'),
  'field.phoneHint': ('9X XXX XXX', '9X XXX XXX'),
  'field.email': ('Email', 'البريد الإلكتروني'),
  'field.password': ('Password', 'كلمة المرور'),
  'field.confirmPassword': ('Confirm password', 'تأكيد كلمة المرور'),
  'field.newPassword': ('New password', 'كلمة المرور الجديدة'),
  'field.businessName': ('Business name', 'اسم الشركة'),
  'field.agencyName': ('Agency / brokerage name', 'اسم الوكالة / شركة الوساطة'),
  'field.serviceType': ('Service type', 'نوع الخدمة'),
  'field.show': ('Show password', 'إظهار كلمة المرور'),
  'field.hide': ('Hide password', 'إخفاء كلمة المرور'),
  'service.interior': ('Interior', 'داخلي'),
  'service.exterior': ('Exterior', 'خارجي'),
  'service.both': ('Both', 'كلاهما'),
  'err.email': ('Enter a valid email address.', 'أدخل بريداً إلكترونياً صحيحاً.'),
  'err.phone': ('Enter an 8-digit Oman mobile number.', 'أدخل رقم جوال عُماني من 8 أرقام.'),
  'err.passwordRules': ('Use at least 8 characters, including one uppercase letter and one number.', 'استخدم 8 أحرف على الأقل، منها حرف كبير واحد ورقم واحد.'),
  'err.passwordShort': ('Use at least {n} characters.', 'استخدم {n} أحرف على الأقل.'),
  'err.passwordMismatch': ('Passwords do not match.', 'كلمتا المرور غير متطابقتين.'),
  'err.consent': ('Please accept to continue.', 'يرجى الموافقة للمتابعة.'),
  // login
  'login.title': ('Welcome back', 'مرحباً بعودتك'),
  'login.sub': ('Log in to continue your property journey.', 'سجّل الدخول لمتابعة رحلتك العقارية.'),
  'login.action': ('Log in', 'تسجيل الدخول'),
  'login.forgot': ('Forgot password?', 'نسيت كلمة المرور؟'),
  'login.noAccount': ('New to AQARATI? Create an account', 'جديد في عقاراتي؟ أنشئ حساباً'),
  'login.invalid': ('The email or password is not correct.', 'البريد الإلكتروني أو كلمة المرور غير صحيحة.'),
  'login.tooMany': ('Too many attempts. Please wait a moment and try again.', 'محاولات كثيرة. انتظر قليلاً ثم حاول مرة أخرى.'),
  'login.unavailable': ('Sign-in is not connected yet.', 'تسجيل الدخول غير متاح بعد.'),
  // forgot / reset
  'forgot.title': ('Forgot your password?', 'نسيت كلمة المرور؟'),
  'forgot.sub': ('Enter your email and we will send a reset link if an account exists.', 'أدخل بريدك الإلكتروني وسنرسل رابط إعادة التعيين إن كان هناك حساب.'),
  'forgot.action': ('Send reset link', 'إرسال رابط إعادة التعيين'),
  'forgot.sentTitle': ('Check your email', 'تحقق من بريدك'),
  'forgot.sentBody': ('If an account exists for that address, a reset link is on its way.', 'إن كان هناك حساب بهذا العنوان، فقد أُرسل إليه رابط إعادة التعيين.'),
  'forgot.toLogin': ('Back to log in', 'العودة لتسجيل الدخول'),
  'reset.title': ('Choose a new password', 'اختر كلمة مرور جديدة'),
  'reset.action': ('Save new password', 'حفظ كلمة المرور'),
  'reset.done': ('You can now log in with your new password.', 'يمكنك الآن تسجيل الدخول بكلمة المرور الجديدة.'),
  'reset.expired': ('This reset link has expired or was already used. Request a new one.', 'انتهت صلاحية رابط إعادة التعيين أو استُخدم مسبقاً. اطلب رابطاً جديداً.'),
  'reset.requestNew': ('Request a new link', 'طلب رابط جديد'),
  // signup
  'signup.step': ('Step {a} of {b}', 'الخطوة {a} من {b}'),
  'signup.stepYou': ('About you', 'عنك'),
  'signup.stepBusiness': ('Your business', 'عملك'),
  'signup.stepAccount': ('Account & consent', 'الحساب والموافقة'),
  'signup.consent': ('I agree to the AQARATI Terms of Use and Privacy Policy.', 'أوافق على شروط الاستخدام وسياسة الخصوصية في عقاراتي.'),
  'signup.create': ('Create account', 'إنشاء الحساب'),
  'signup.draftSaved': ('Your answers are saved on this device (never your password or documents).', 'تُحفظ إجاباتك على هذا الجهاز (ولا تُحفظ كلمة المرور أو المستندات).'),
  'signup.conflict': ('We could not create the account with those details. Try logging in, or use different details.', 'تعذّر إنشاء الحساب بهذه البيانات. جرّب تسجيل الدخول أو استخدم بيانات مختلفة.'),
  'signup.validation': ('Please check the highlighted fields.', 'يرجى مراجعة الحقول المحددة.'),
  'signup.t.userToShop': ('Create your account', 'أنشئ حسابك'),
  'signup.t.realEstateAgent': ('Join as a real estate agent', 'انضم كوسيط عقاري'),
  'signup.t.constructionCompany': ('Register your construction company', 'سجّل شركة المقاولات'),
  'signup.t.propertyDevelopmentCompany': ('Register your development company', 'سجّل شركة التطوير العقاري'),
  'signup.t.buildingArchitecture': ('Register your architecture practice', 'سجّل مكتبك المعماري'),
  'signup.t.interiorExteriorDesign': ('Register your design practice', 'سجّل مكتب التصميم'),
  'signup.docsLater': ('You will upload your documents after your phone is verified.', 'ستحمّل مستنداتك بعد التحقق من رقم جوالك.'),
  'signup.noDocs': ('No documents are needed to sign up.', 'لا حاجة إلى مستندات للتسجيل.'),
  // otp
  'otp.title': ('Verify your phone', 'تحقق من رقم جوالك'),
  'otp.sending': ('Sending your code…', 'جارٍ إرسال الرمز…'),
  'otp.sent': ('We sent a 6-digit code to +968 ••••{last4}.', 'أرسلنا رمزاً من 6 أرقام إلى ‎+968 ••••{last4}.'),
  'otp.sentNoPhone': ('We sent a 6-digit code to your phone.', 'أرسلنا رمزاً من 6 أرقام إلى جوالك.'),
  'otp.verifying': ('Verifying…', 'جارٍ التحقق…'),
  'otp.invalid': ('That code is not correct. Check it and try again.', 'الرمز غير صحيح. تحقق منه وحاول مرة أخرى.'),
  'otp.expired': ('This code has expired. Request a new one.', 'انتهت صلاحية الرمز. اطلب رمزاً جديداً.'),
  'otp.rateLimited': ('Too many attempts. Please wait before trying again.', 'محاولات كثيرة. انتظر قبل المحاولة مرة أخرى.'),
  'otp.error': ('We could not complete verification. Please try again.', 'تعذّر إكمال التحقق. حاول مرة أخرى.'),
  'otp.resend': ('Resend code', 'إعادة إرسال الرمز'),
  'otp.resendIn': ('Resend in {s}s', 'إعادة الإرسال بعد {s} ث'),
  'otp.send': ('Send code', 'إرسال الرمز'),
  'otp.verified': ('Phone verified', 'تم التحقق من الجوال'),
  'otp.demoHint': ('DEMO: use code 123456', 'تجريبي: استخدم الرمز 123456'),
  'otp.codeLabel': ('Verification code', 'رمز التحقق'),
  // account active
  'active.title': ('Your account is active', 'حسابك نشط'),
  'active.buyer': ('You can now browse, search and book on AQARATI.', 'يمكنك الآن التصفح والبحث والحجز في عقاراتي.'),
  'active.business': ('Your account is active. This is not yet an approved business role: add your documents so we can verify it.', 'حسابك نشط. هذا ليس دوراً تجارياً معتمداً بعد: أضف مستنداتك لنتحقق منه.'),
  'active.home': ('Go to home', 'الانتقال إلى الرئيسية'),
  'active.docs': ('Add documents', 'إضافة المستندات'),
  // documents
  'docs.title': ('Your documents', 'مستنداتك'),
  'docs.sub': ('Upload each document. Each one is sent and checked on its own.', 'حمّل كل مستند. يُرسل كل مستند ويُفحص بشكل مستقل.'),
  'docs.rules': ('PDF, JPG or PNG · up to 10 MB', 'PDF أو JPG أو PNG · حتى 10 ميغابايت'),
  'docs.submit': ('Submit for verification', 'إرسال للتحقق'),
  'docs.submitHelp': ('Upload every document to continue.', 'حمّل جميع المستندات للمتابعة.'),
  'docs.fourEyes': ('Development companies go through a two-step review: a reviewer first, then a senior reviewer.', 'تمر شركات التطوير العقاري بمراجعتين: مراجع أولاً ثم مراجع أول.'),
  'docs.expiry': ('Expiry date', 'تاريخ الانتهاء'),
  'docs.setExpiry': ('Set expiry date', 'تحديد تاريخ الانتهاء'),
  'docs.expiryNeeded': ('Set the expiry date first.', 'حدّد تاريخ الانتهاء أولاً.'),
  'docs.choose': ('Choose file', 'اختيار ملف'),
  'docs.replace': ('Replace file', 'استبدال الملف'),
  'docs.retry': ('Retry', 'إعادة المحاولة'),
  'docs.state.idle': ('Not uploaded', 'لم يُحمَّل'),
  'docs.state.selecting': ('Checking file…', 'جارٍ فحص الملف…'),
  'docs.state.uploading': ('Uploading {p}%', 'جارٍ الرفع {p}%'),
  'docs.state.processing': ('Scanning…', 'جارٍ الفحص…'),
  'docs.state.success': ('Received · pending review', 'تم الاستلام · قيد المراجعة'),
  'docs.state.failed': ('Upload failed', 'فشل الرفع'),
  'docs.state.retrying': ('Retrying…', 'جارٍ إعادة المحاولة…'),
  'docs.state.rejected': ('Needs replacing', 'يحتاج إلى استبدال'),
  'docs.err.type': ('Use a PDF, JPG or PNG file.', 'استخدم ملف PDF أو JPG أو PNG.'),
  'docs.err.size': ('The file is larger than 10 MB.', 'حجم الملف أكبر من 10 ميغابايت.'),
  'docs.err.pick': ('We could not open that file.', 'تعذّر فتح هذا الملف.'),
  'doc.photoId': ('Photo ID', 'الهوية الشخصية'),
  'doc.agentLicence': ('Agent licence', 'رخصة الوسيط'),
  'doc.supportingDocument': ('Supporting document', 'مستند داعم'),
  'doc.crCertificate': ('CR certificate', 'شهادة السجل التجاري'),
  'doc.municipalLicence': ('Municipal licence', 'الرخصة البلدية'),
  'doc.officialCorporateRegistration': ('Official corporate registration', 'التسجيل الرسمي للشركة'),
  'doc.activityLicences': ('Activity licence(s)', 'رخصة / رخص النشاط'),
  'doc.developerLicence': ('Developer licence', 'رخصة المطوّر'),
  // verification
  'ver.title': ('Verification', 'التحقق'),
  'ver.requestedRole': ('Requested role', 'الدور المطلوب'),
  'ver.submitted': ('Submitted {d}', 'أُرسل في {d}'),
  'ver.submittedLabel': ('Submission', 'الإرسال'),
  'ver.notSubmitted': ('Not submitted yet', 'لم يُرسل بعد'),
  'ver.documents': ('Documents', 'المستندات'),
  'ver.missing': ('Still missing', 'لا يزال ناقصاً'),
  'ver.correction': ('Needs correction', 'يحتاج إلى تصحيح'),
  'ver.reason': ('Reason', 'السبب'),
  'ver.next': ('Next step', 'الخطوة التالية'),
  'ver.expires': ('Expires {d}', 'ينتهي في {d}'),
  'badge.draft': ('Draft', 'مسودة'),
  'badge.pendingVerification': ('Under review', 'قيد المراجعة'),
  'badge.awaitingSecond': ('Awaiting second approval', 'بانتظار الموافقة الثانية'),
  'badge.approved': ('Approved', 'معتمد'),
  'badge.resubmissionRequired': ('Resubmission required', 'مطلوب إعادة الإرسال'),
  'badge.rejected': ('Rejected', 'مرفوض'),
  'badge.suspended': ('Suspended', 'معلّق'),
  'ver.body.draft': ('Your documents have not been submitted yet. Add them to start verification.', 'لم تُرسل مستنداتك بعد. أضفها لبدء التحقق.'),
  'ver.body.pending': ('Your documents are with our reviewers. We will notify you when there is an update.', 'مستنداتك لدى المراجعين. سنُعلمك عند وجود تحديث.'),
  'ver.body.second': ('A first reviewer has approved your submission. A senior reviewer completes the final approval.', 'وافق مراجع أول على طلبك. يُكمل مراجع أول الموافقة النهائية.'),
  'ver.body.approved': ('Your business role is approved.', 'تم اعتماد دورك التجاري.'),
  'ver.body.resubmission': ('Some documents need to be replaced. Your other details are kept.', 'تحتاج بعض المستندات إلى استبدال. تبقى بقية بياناتك كما هي.'),
  'ver.body.rejected': ('This request was not approved. See the reason below.', 'لم تتم الموافقة على هذا الطلب. راجع السبب أدناه.'),
  'ver.body.suspended': ('This role is suspended. Business capabilities and related content are not available while it is suspended.', 'هذا الدور معلّق. لا تتوفر الصلاحيات التجارية والمحتوى المرتبط به أثناء التعليق.'),
  'ver.action.docs': ('Add documents', 'إضافة المستندات'),
  'ver.action.fix': ('Replace documents', 'استبدال المستندات'),
  'ver.action.home': ('Go to home', 'الانتقال إلى الرئيسية'),
  'ver.action.refresh': ('Refresh status', 'تحديث الحالة'),
  'ver.retryLoad': ('We could not load your verification status.', 'تعذّر تحميل حالة التحقق.'),
  'ver.demoTitle': ('DEMO: simulate reviewer decision', 'تجريبي: محاكاة قرار المراجع'),
  'reason.DOC_UNREADABLE': ('The document could not be read clearly.', 'تعذّرت قراءة المستند بوضوح.'),
  'reason.DOC_EXPIRED': ('The document has expired.', 'انتهت صلاحية المستند.'),
  'reason.DOC_MISMATCH': ('The document does not match the details provided.', 'المستند لا يطابق البيانات المقدمة.'),
  'reason.unknown': ('A reviewer asked for this document to be replaced.', 'طلب المراجع استبدال هذا المستند.'),
  // resubmit
  'resub.title': ('Replace documents', 'استبدال المستندات'),
  'resub.sub': ('Only the documents below need replacing. Everything else stays as submitted.', 'المستندات أدناه فقط تحتاج إلى استبدال. وبقية البيانات كما أُرسلت.'),
  'resub.submit': ('Resubmit for review', 'إعادة الإرسال للمراجعة'),
  'resub.none': ('Nothing needs replacing right now.', 'لا شيء يحتاج إلى استبدال الآن.'),
  'resub.done': ('Resubmitted. Your documents are back with our reviewers.', 'أُعيد الإرسال. عادت مستنداتك إلى المراجعين.'),
  'pw.req.length': ('At least 8 characters', '8 أحرف على الأقل'),
  'pw.req.upper': ('One uppercase letter', 'حرف كبير واحد'),
  'pw.req.number': ('One number', 'رقم واحد'),
  'otp.change': ('Change number', 'تغيير الرقم'),
  'otp.didnt': ("Didn't get a code?", 'لم يصلك الرمز؟'),
  'secure.note': ('Your details are protected and used only to set up your account.', 'بياناتك محمية وتُستخدم فقط لإعداد حسابك.'),
  'otp.expiresHint': ('The code is valid for 15 minutes.', 'الرمز صالح لمدة 15 دقيقة.'),
  'otp.verifyCta': ('Verify & continue', 'تحقق وتابع'),
  'otp.continuing': ('Taking you to your account…', 'ننقلك إلى حسابك…'),
  'login.secure': ('Your data is secure. We use industry-standard protection for your information.', 'بياناتك آمنة. نستخدم حماية معيارية لمعلوماتك.'),
  'login.createShort': ('Create account', 'إنشاء حساب'),
  'forgot.different': ('Use a different email', 'استخدام بريد آخر'),
  'forgot.safe': ('We only send a reset link to the email linked to your account.', 'نرسل رابط إعادة التعيين فقط إلى البريد المرتبط بحسابك.'),
  'reset.sub': ('Choose a strong password you have not used elsewhere.', 'اختر كلمة مرور قوية لم تستخدمها في مكان آخر.'),
  'reset.doneTitle': ('Password updated', 'تم تحديث كلمة المرور'),
  'reset.match': ('Passwords match.', 'كلمتا المرور متطابقتان.'),
  'vintro.title': ('Verify your business', 'وثّق عملك'),
  'vintro.sub': ('A short, one-time check so people can trust who they deal with on AQARATI.', 'فحص قصير لمرة واحدة ليثق الناس بمن يتعاملون معه في عقاراتي.'),
  'vintro.why.title': ('Why we verify', 'لماذا نتحقق'),
  'vintro.why.body': ('Verification keeps AQARATI authentic and safe: real businesses, trusted listings and a more reliable Oman property ecosystem.', 'يبقي التحقق عقاراتي أصيلة وآمنة: أعمال حقيقية وإعلانات موثوقة ومنظومة عقارية أكثر موثوقية في عُمان.'),
  'vintro.what.title': ('What we check', 'ما الذي نفحصه'),
  'vintro.what.1': ('Business registration', 'السجل التجاري'),
  'vintro.what.2': ('Licences', 'التراخيص'),
  'vintro.what.3': ('Business identity and authorised representative', 'هوية الشركة والممثل المفوّض'),
  'vintro.what.4': ('Document authenticity', 'صحة المستندات'),
  'vintro.yours': ('Your required documents', 'مستنداتك المطلوبة'),
  'vintro.cta': ('Add my documents', 'إضافة مستنداتي'),
  'docs.required': ('Required', 'مطلوب'),
  'docs.review': ('Review application', 'مراجعة الطلب'),
  'docs.state.accepted': ('Verified', 'تم التحقق'),
  'docdesc.photoId': ('A clear photo of your valid ID.', 'صورة واضحة لهويتك السارية.'),
  'docdesc.agentLicence': ('Your current real estate agent licence.', 'رخصة الوسيط العقاري السارية.'),
  'docdesc.supportingDocument': ('Any document that supports your application.', 'أي مستند يدعم طلبك.'),
  'docdesc.crCertificate': ('Your commercial registration certificate.', 'شهادة السجل التجاري.'),
  'docdesc.municipalLicence': ('Your current municipal licence.', 'الرخصة البلدية السارية.'),
  'docdesc.officialCorporateRegistration': ('Your official corporate registration.', 'التسجيل الرسمي لشركتك.'),
  'docdesc.activityLicences': ('The licence(s) covering your activities.', 'الرخصة أو الرخص التي تغطي أنشطتك.'),
  'docdesc.developerLicence': ('Your property developer licence.', 'رخصة المطوّر العقاري.'),
  'review.title': ('Review your application', 'راجع طلبك'),
  'review.sub': ('Check everything before you submit.', 'تحقق من كل شيء قبل الإرسال.'),
  'review.business': ('Business', 'العمل'),
  'review.name': ('Name', 'الاسم'),
  'review.role': ('Role', 'الدور'),
  'review.documents': ('Documents', 'المستندات'),
  'review.consent': ('Consent', 'الموافقة'),
  'review.consentBody': ('You accepted the Terms of Use and Privacy Policy when you created your account.', 'وافقت على شروط الاستخدام وسياسة الخصوصية عند إنشاء حسابك.'),
  'review.edit': ('Edit', 'تعديل'),
  'review.submit': ('Submit application', 'إرسال الطلب'),
  'review.incomplete': ('Upload every required document to submit.', 'حمّل جميع المستندات المطلوبة للإرسال.'),
  'submitted.title': ('Application submitted', 'تم إرسال الطلب'),
  'submitted.body': ('Your application has been submitted for verification. We will notify you when there is an update.', 'تم إرسال طلبك للتحقق. سنُعلمك عند وجود تحديث.'),
  'submitted.ref': ('Reference', 'المرجع'),
  'submitted.cta': ('View application status', 'عرض حالة الطلب'),
  'vh.draft': ('Add your documents', 'أضف مستنداتك'),
  'vh.pending': ('Your application is under review', 'طلبك قيد المراجعة'),
  'vh.second': ('Awaiting second approval', 'بانتظار الموافقة الثانية'),
  'vh.approved': ('You are verified', 'تم توثيقك'),
  'vh.resub': ('Resubmission required', 'مطلوب إعادة الإرسال'),
  'vh.rejected': ('Application not approved', 'لم تتم الموافقة على الطلب'),
  'vh.suspended': ('Role suspended', 'الدور معلّق'),
  'tl.submitted': ('Submitted', 'تم الإرسال'),
  'tl.review': ('Under review', 'قيد المراجعة'),
  'tl.second': ('Awaiting second approval', 'بانتظار الموافقة الثانية'),
  'tl.approved': ('Approved', 'معتمد'),
  'ver.viewApplication': ('View application', 'عرض الطلب'),
  'ver.nothingNeeded': ('Nothing is needed from you right now.', 'لا يلزمك أي إجراء الآن.'),
  'ver.decided': ('Decision on {d}', 'القرار بتاريخ {d}'),
  'expiry.expired': ('Expired {d}', 'انتهت في {d}'),
  'expiry.soon': ('Expires soon · {d}', 'تنتهي قريباً · {d}'),
  'ver.action.continue': ('Continue', 'متابعة'),
  'det.title': ('Application details', 'تفاصيل الطلب'),
  'det.reference': ('Reference', 'المرجع'),
  'det.submittedAt': ('Submitted', 'تاريخ الإرسال'),
  'det.type': ('Business type', 'نوع العمل'),
  'det.company': ('Company', 'الشركة'),
  'det.status': ('Status', 'الحالة'),
  'det.locked': ('Editing is unavailable while your application is under review.', 'التعديل غير متاح أثناء مراجعة طلبك.'),
  'det.refPending': ('Not available yet', 'غير متاح بعد'),
  'resub.reviewCta': ('Review changes', 'مراجعة التغييرات'),
  'resub.why': ('Why', 'السبب'),
  'resub.alreadyOk': ('No action needed', 'لا يلزم إجراء'),
  'rr.title': ('Review changes', 'مراجعة التغييرات'),
  'rr.sub': ('Confirm what you are resubmitting.', 'أكّد ما ستعيد إرساله.'),
  'rr.updated': ('Updated', 'تم التحديث'),
  'rr.approved': ('Already approved', 'معتمد مسبقاً'),
  'rr.confirm': ('Resubmit application', 'إعادة إرسال الطلب'),
  'rr.nothing': ('No documents were changed.', 'لم يتغير أي مستند.'),
  'rd.title': ('Application resubmitted', 'أُعيد إرسال الطلب'),
  'rd.body': ('Your updated documents are back with our reviewers. Your application is under review again.', 'عادت مستنداتك المحدّثة إلى المراجعين. طلبك قيد المراجعة مجدداً.'),
  'rd.changed': ('What changed', 'ما الذي تغيّر'),
  'rd.at': ('Resubmitted {d}', 'أُعيد الإرسال في {d}'),
  'ap.title': ('You are verified', 'تم توثيقك'),
  'ap.sub': ('Your business has been approved on AQARATI.', 'تم اعتماد عملك في عقاراتي.'),
  'ap.1': ('Documents verified', 'تم التحقق من المستندات'),
  'ap.2': ('Business approved', 'تم اعتماد العمل'),
  'ap.3': ('Profile activated', 'تم تفعيل الملف'),
  'ap.4': ('Professional workspace ready', 'مساحة العمل المهنية جاهزة'),
  'sum.title': ('Verified profile', 'الملف الموثّق'),
  'sum.identity': ('Verified business', 'العمل الموثّق'),
  'sum.at': ('Verified on', 'تاريخ التوثيق'),
  'sum.docs': ('Verified documents', 'المستندات الموثّقة'),
  'sum.profile': ('Profile status', 'حالة الملف'),
  'sum.profileActive': ('Active', 'نشط'),
  'sum.workspace': ('Workspace access', 'الوصول إلى مساحة العمل'),
  'sum.cta': ('Enter workspace', 'دخول مساحة العمل'),
  'nav.home': ('Home', 'الرئيسية'),
  'nav.explore': ('Explore', 'استكشف'),
  'nav.activity': ('Activity', 'النشاط'),
  'nav.account': ('Account', 'الحساب'),
  'home.title': ('Welcome to AQARATI', 'مرحبًا بك في عقاراتي'),
  'home.verified': ('Your business is verified', 'تم التحقق من نشاطك'),
  'home.verification': ('Verification', 'التحقق'),
  'home.viewStatus': ('View application status', 'عرض حالة الطلب'),
  'home.userBody': ('Your account is active.', 'حسابك نشط.'),
  'home.soon': ('Property search and listings arrive in the next phase of the app.', 'البحث عن العقارات والإعلانات ستصل في المرحلة القادمة من التطبيق.'),
  'explore.title': ('Explore', 'استكشف'),
  'activity.title': ('Activity', 'النشاط'),
  'activity.empty': ('Nothing here yet. Updates about your account will appear here.', 'لا شيء هنا بعد. ستظهر هنا تحديثات حسابك.'),
  'account.title': ('Account', 'الحساب'),
  'account.role': ('Role', 'الدور'),
  'account.phone': ('Mobile number', 'رقم الجوال'),
  'account.language': ('Language', 'اللغة'),
  'account.signOut': ('Sign out', 'تسجيل الخروج'),
  'ws.title': ('Your workspace is ready', 'مساحة عملك جاهزة'),
  'ws.sub': ('Here is what your approved role unlocks.', 'هذا ما يتيحه دورك المعتمد.'),
  'ws.cta': ('Open workspace', 'فتح مساحة العمل'),
  'ws.cap.agent.1': ('Switch between Buyer and Agent', 'التبديل بين مشترٍ ووسيط'),
  'ws.cap.agent.2': ('Create and manage listings', 'إنشاء الإعلانات وإدارتها'),
  'ws.cap.agent.3': ('Manage viewing availability', 'إدارة مواعيد المعاينة'),
  'ws.cap.pro.1': ('Your company profile is visible in the directory', 'ملف شركتك ظاهر في الدليل'),
  'ws.cap.pro.2': ('Keep your profile and documents up to date', 'أبقِ ملفك ومستنداتك محدّثة'),
  'ws.cap.dev.1': ('Your developer profile is live after approval', 'ملف المطوّر ظاهر بعد الاعتماد'),
  'ws.cap.dev.2': ('Create and manage your own projects (each is reviewed)', 'أنشئ مشاريعك وأدرها (يخضع كل مشروع للمراجعة)'),
};
